/* ============================================================
   recettes.js — base de recettes de départ (window.RECETTES).
   Champs : id, nom, temps (min), portions, protein, saison,
            ingredients (noms simples, servent au matching promo),
            etapes.
   Enrichissez librement : plus il y a de recettes, meilleur est
   le menu. Les noms d'ingrédients doivent rester simples et au
   singulier quand c'est possible (poireau, tomate…) pour bien
   matcher les promos.
   ============================================================ */
window.RECETTES = [
  { id: "r01", nom: "Poulet rôti, poireaux fondants", temps: 55, portions: 4, protein: "poulet", saison: ["auto", "hiver"],
    ingredients: ["poulet", "poireau", "pomme de terre", "beurre", "thym"],
    etapes: ["Préchauffer le four à 200°C.", "Enfourner le poulet 45 min avec les pommes de terre.", "Faire fondre les poireaux au beurre 15 min.", "Servir ensemble."] },
  { id: "r02", nom: "Pâtes crémées au saumon", temps: 25, portions: 4, protein: "poisson", saison: ["toute"],
    ingredients: ["saumon", "pâtes", "crème", "citron", "aneth"],
    etapes: ["Cuire les pâtes al dente.", "Émincer le saumon, le saisir 3 min.", "Ajouter crème et citron, mélanger.", "Lier avec les pâtes, parsemer d'aneth."] },
  { id: "r03", nom: "Gratin de pommes de terre", temps: 50, portions: 4, protein: "végé", saison: ["auto", "hiver"],
    ingredients: ["pomme de terre", "crème", "emmental", "ail", "muscade"],
    etapes: ["Émincer les pommes de terre.", "Disposer en couches avec crème et ail.", "Couvrir d'emmental.", "Enfourner 40 min à 180°C."] },
  { id: "r04", nom: "Omelette aux herbes, salade", temps: 15, portions: 4, protein: "oeuf", saison: ["toute"],
    ingredients: ["oeuf", "salade", "persil", "ciboulette", "huile"],
    etapes: ["Battre les œufs avec les herbes.", "Cuire à la poêle 4 min.", "Servir avec la salade assaisonnée."] },
  { id: "r05", nom: "Riz sauté au poulet", temps: 20, portions: 4, protein: "poulet", saison: ["toute"],
    ingredients: ["riz", "poulet", "oeuf", "carotte", "sauce soja"],
    etapes: ["Cuire le riz.", "Saisir le poulet et les carottes.", "Ajouter le riz et l'œuf brouillé.", "Déglacer à la sauce soja."] },
  { id: "r06", nom: "Carpaccio de bœuf & frites", temps: 20, portions: 4, protein: "boeuf", saison: ["ete", "print"],
    ingredients: ["carpaccio", "frites", "salade", "parmesan", "huile"],
    etapes: ["Cuire les frites au four.", "Dresser le carpaccio, arroser d'huile.", "Copeaux de parmesan et salade."] },
  { id: "r07", nom: "Brochettes grillées, riz", temps: 30, portions: 4, protein: "boeuf", saison: ["ete"],
    ingredients: ["brochette", "poivron", "oignon", "riz"],
    etapes: ["Monter les brochettes avec poivron et oignon.", "Griller 10 min.", "Servir avec le riz."] },
  { id: "r08", nom: "Compote & yaourt", temps: 10, portions: 4, protein: "dessert", saison: ["toute"],
    ingredients: ["compote", "yaourt", "miel"],
    etapes: ["Répartir la compote.", "Ajouter le yaourt et un trait de miel."] },
  { id: "r09", nom: "Tartines de saumon", temps: 15, portions: 4, protein: "poisson", saison: ["toute"],
    ingredients: ["saumon", "pain", "citron", "salade", "beurre"],
    etapes: ["Toaster le pain beurré.", "Déposer le saumon.", "Citron et salade à côté."] },
  { id: "r10", nom: "Salade composée", temps: 15, portions: 4, protein: "végé", saison: ["ete"],
    ingredients: ["salade", "tomate", "oeuf", "thon", "maïs"],
    etapes: ["Cuire les œufs durs.", "Mélanger salade, tomate, thon, maïs.", "Assaisonner."] },
  { id: "r11", nom: "Steak frites", temps: 20, portions: 4, protein: "boeuf", saison: ["toute"],
    ingredients: ["steak", "frites", "salade"],
    etapes: ["Cuire les frites.", "Saisir le steak 2 min par face.", "Servir avec salade."] },
  { id: "r12", nom: "Gratin de courgettes", temps: 40, portions: 4, protein: "végé", saison: ["ete"],
    ingredients: ["courgette", "crème", "emmental", "oeuf"],
    etapes: ["Émincer et faire revenir les courgettes.", "Mélanger avec crème et œuf.", "Gratiner 25 min."] },
  { id: "r13", nom: "Poêlée de dinde aux légumes", temps: 25, portions: 4, protein: "dinde", saison: ["toute"],
    ingredients: ["dinde", "poivron", "courgette", "oignon", "riz"],
    etapes: ["Saisir la dinde.", "Ajouter les légumes.", "Servir sur riz."] },
  { id: "r14", nom: "Quiche lorraine", temps: 45, portions: 4, protein: "oeuf", saison: ["toute"],
    ingredients: ["oeuf", "crème", "lardon", "pâte", "emmental"],
    etapes: ["Garnir la pâte de lardons.", "Verser œufs+crème.", "Cuire 35 min à 180°C."] },
  { id: "r15", nom: "Curry de pois chiches", temps: 30, portions: 4, protein: "végé", saison: ["toute"],
    ingredients: ["pois chiche", "tomate", "oignon", "riz", "lait de coco"],
    etapes: ["Revenir oignon et épices.", "Ajouter pois chiches et tomate.", "Mijoter, servir sur riz."] },
  { id: "r16", nom: "Papillote de cabillaud", temps: 25, portions: 4, protein: "poisson", saison: ["toute"],
    ingredients: ["cabillaud", "courgette", "tomate", "citron", "huile"],
    etapes: ["Déposer poisson et légumes en papillote.", "Citron et huile.", "Four 20 min à 190°C."] },
  { id: "r17", nom: "Chili con carne", temps: 40, portions: 4, protein: "boeuf", saison: ["auto", "hiver"],
    ingredients: ["boeuf", "haricot rouge", "tomate", "oignon", "riz"],
    etapes: ["Saisir la viande.", "Ajouter haricots, tomate, épices.", "Mijoter 30 min, servir sur riz."] },
  { id: "r18", nom: "Croque-monsieur & salade", temps: 15, portions: 4, protein: "porc", saison: ["toute"],
    ingredients: ["pain", "jambon", "emmental", "salade"],
    etapes: ["Monter les croques.", "Passer au four 8 min.", "Servir avec salade."] },
  { id: "r19", nom: "Soupe de légumes", temps: 35, portions: 4, protein: "végé", saison: ["auto", "hiver"],
    ingredients: ["poireau", "carotte", "pomme de terre", "oignon"],
    etapes: ["Éplucher et couper les légumes.", "Cuire 25 min.", "Mixer, assaisonner."] },
  { id: "r20", nom: "Pâtes bolognaise", temps: 35, portions: 4, protein: "boeuf", saison: ["toute"],
    ingredients: ["pâtes", "boeuf", "tomate", "oignon", "carotte"],
    etapes: ["Revenir oignon, carotte, viande.", "Ajouter tomate, mijoter 20 min.", "Servir sur pâtes."] },
  { id: "r21", nom: "Wok de crevettes", temps: 20, portions: 4, protein: "poisson", saison: ["toute"],
    ingredients: ["crevette", "nouilles", "poivron", "carotte", "sauce soja"],
    etapes: ["Sauter les légumes.", "Ajouter crevettes et nouilles.", "Déglacer à la sauce soja."] },
  { id: "r22", nom: "Hachis parmentier", temps: 45, portions: 4, protein: "boeuf", saison: ["auto", "hiver"],
    ingredients: ["boeuf", "pomme de terre", "oignon", "beurre", "lait"],
    etapes: ["Préparer une purée.", "Faire revenir la viande hachée.", "Superposer, gratiner 20 min."] },
  { id: "r23", nom: "Salade de pâtes au thon", temps: 15, portions: 4, protein: "poisson", saison: ["ete"],
    ingredients: ["pâtes", "thon", "tomate", "maïs", "oeuf"],
    etapes: ["Cuire et refroidir les pâtes.", "Mélanger thon, tomate, maïs, œufs.", "Assaisonner."] },
  { id: "r24", nom: "Poulet basquaise", temps: 40, portions: 4, protein: "poulet", saison: ["ete", "auto"],
    ingredients: ["poulet", "poivron", "tomate", "oignon", "riz"],
    etapes: ["Saisir le poulet.", "Ajouter poivrons, tomate, oignon.", "Mijoter 30 min, servir sur riz."] },
];
